# Generated by Django 2.2.16 on 2023-03-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230310_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_following',
            new_name='is_subscribed',
        ),
    ]
